### ISSUE TITLE
Need to migrate to Home Assistant set_percentage() API instead of low/medium/high.

### ISSUE THREAD

**Issue by rsnodgrass** [rsnodgrass/hass-lunos#8]
HA recently deprecated the low/medium/high settings for a % based mapping instead. Need to figure out how this applies to LUNOS.

**Comment by rsnodgrass** [comment]
Attempted to quickly make changes to allow set_percentage to work with HASS 2022.06+. Testing.

**Comment by rsnodgrass** [comment]
Release 0.2.0

**Comment by Henry-Sir** [comment]
Hi,

Thank you for the release 0.2.0.
Yesterday i updated my Home Assistant to 2022.6.7 (from 2022.3) due to this release.


The status of the fans is displayed correctly but unfortunately the speed / mode can not be changed.

When changing the mode, the following error is displayed:
`Failed to call service fan/set_preset_mode. async_set_preset_mode() got an unexpected keyword argument 'preset_mode'.`

![grafik](https://user-images.githubusercontent.com/75314095/176484353-cdb8d7ad-61a1-42ef-8e9b-665d42d5ba72.png)


When changing the speed (via percent) nothing happens (it jumps back to the original value).

Have I configured something wrong?




![grafik](https://user-images.githubusercontent.com/75314095/176484944-3556a3fe-58f1-4131-b8b8-5feb4bc3ec57.png)
